Push-Away-Range: 3
Push-Away-Launch-X: .7
Push-Away-Launch-Y: .5
Usage-Cooldown: 5
Wand:
  Material: "RECORD_3"
  Name: "&a&lPushAway Wand"
  Lore:
    - "&7Right click to &epush &7players away!"
    - "&7Works up to &e%range% blocks"
Sound:
  On-Push:
    Enabled: true
    Sound: "BLOCK_ANVIL_PLACE"
    Volume: 1.0
    Pitch: 1.0
  When-Pushed:
    Enabled: true
    Sound: "ENTITY_BLAZE_SHOOT"
    Volume: 1.0
    Pitch: 1.0
Messages:
  Permission: "&cYou do not have permission to use this command!"
  Given-Wand: "&7You have been given a &a&lPushAway Wand&7!"
  Give-Other-Wand: "&7You have given &e%player% &7a &a&lPushAway Wand&7!"
  Pushed-Players: "&7You have &e&lLAUNCHED &a%num% &7players away from you!"
  Pushed-By-Player: "&7You have been &epushed away &7by &c%player%&7!"
  No-Players-Nearby: "&7There are no players nearby!"
  Cooldown: "&cYou are on cooldown for &e%time% &cmore seconds!"